name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.1' # minimal supported
          - '1.6' # current LTS
          - '1' # current stable
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    steps:
      - name: Git checkout repository
        uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      - name: Process coverage
        if: ${{ matrix.version == '1' && matrix.os =='ubuntu-latest' }}
        uses: julia-actions/julia-processcoverage@v1
      - name: Submit to Coveralls
        if: ${{ matrix.version == '1' && matrix.os =='ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
